apimServiceName: pkapimlabprod
loggers:
    - name: pkapimlabprod-ai
      loggerType: applicationInsights
      description: prod app insights
      resourceId: "/subscriptions/fe5f965f-9f7f-4846-a2c7-957be7ad6de1/resourceGroups/pkapimlabprod-rg/providers/microsoft.insights/components/pkapimlabprod-ai"
      credentials:
        instrumentationKey: "{{Logger-Credentials--625974d94634611094dc30cc}}"
      isBuffered: true
diagnostics:
   - name: applicationinsights
     verbosity: Error