openapi: 3.0.1
info:
  title: Star Wars API
  description: Do. Or do not. There is no try.
  version: v2
servers:
  - url: https://pkapimlab.azure-api.net/sw/v2
paths:
  /people/:
    get:
      summary: GetPeople
      description: Get characters from the Star Wars Universe
      operationId: getpeople
      responses:
        '200':
          description: 
  '/people/{id}/':
    get:
      summary: GetPeopleById
      description: Get individual characters from the Star Wars universe
      operationId: getpeoplebyid
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  /film:
    get:
      summary: GetFilm
      description: Get film
      operationId: getfilm
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                count: 1
                films:
                  - title: A New Hope
                    release-date: '1977-05-25'
  /favorite:
    get:
      summary: GetFavoritePerson
      operationId: getfavoriteperson
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]